name: Deploy to Production

on:
  push:
    branches:
      - Master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Change to your Node.js version

      - name: Install dependencies
        run: npm install # Replace with your build command

      - name: Build
        run: npm run build # Replace with your build command

      - name: Deploy
        run: |
          # Add your deployment commands here
          # For example, you might use rsync, SCP, or FTP to deploy your files
          # Replace the placeholders with your actual deployment commands
          echo "Deploying to production..."
          rsync -avz --delete ./dist/ user@yourserver:/path/to/deployment
